<?php
	//Log File
	$config["logFile"] = '/tmp/toboggan.log';
	//Log Level
	$config["logLevel"] = 3;
	//Name for the PHP session
	$config["sessionName"] = 'Toboggan';
	//Enable basic auth for file streams/downloads (useful for using external players)
	$config["enable_basic_auth"] = false;
	//Salt for user passwords - autogenerated
	$config["passwordSalt"] = 'xnfZw7qXYOOPiVMwTm9e8A==';
?>