<?php
/************************
* DO NOT EDIT THIS FILE *
*************************/
//bitrate magic number
define("NO_MAX_BITRATE", -1);

//log levels
define("appLog_DEBUG2", 6); // includes error stream from streamer processes
define("appLog_DEBUG", 5);
define("appLog_VERBOSE", 4);
define("appLog_INFO",3);
define("appLog_ERROR", 2);

//permission action ids
define("PERMISSION_STREAMFILE",1);
define("PERMISSION_DOWNLOADFILE",2);
define("PERMISSION_ADMINISTRATOR",3);
define("PERMISSION_ACCESSMEDIASOURCE",4);
define("PERMISSION_ACCESSSTREAMER",5);

//JSON constant
define("JSON_MIME_TYPE", "application/json");
